var currentPage = 1;
const howToPlayGuideText = {
    Page1:[ 
    "When loading into Elemental4, you will be taken into the main menu and given a variety of options to select. These include",
    "Leaderboard, Quick Matchmake, Perk Screen, Settings, Ranked Matchmake, Project Website and Profile.",
    "",
    "Leader board – here you can view the players with the most games won, the top 10 warriors and the players who have gained",
    "the most XP, (experience points). Winning more games will lead to you being seen on these leaderboards and the more games you",
    "win the higher you’ll climb.",
    "",
    "Perk Screen – This allows you to view all the perks available in the game, the perks you have unlocked will be highlighted and",
    "any perks that are yet to be unlocked will be shaded out in a dark grey. When a perk is selected, it will be highlighted pink",
    "to indicate the selection and the cost for acquiring this perk. Perks can be purchased through skill points acquired from ranked",
    "matchmaking. The more games you play the more experience and skill points you can achieve in order to purchase more perks and",
    "increase your chances of winning games.",
    "",
    "Settings – Pressing this button will take you to the settings page where you can change any necessary settings to allow the game",
    "to run more smoothly. There are multiple options you can toggle on and off as well the option to change between 30 and 60fps.",
    "Additionally, the game credits can be viewed by pressing the ‘Game Credits’ button on the page.",
    "",
    "Ranked matchmake – Pressing this button will take you into a search for a match against an opponent who is of the same rank as",
    "you. Winning these games will gain you more XP, bringing you closer to ranking up!",
    ], 
    Page2 :[
    "Project Website – This button will take you to the official website for the Project by redirecting you from the elemental4",
    "website to cybercloudstudios.",
    "",
    "Profile – The profile page shows the profile for your user, this allows you to see how you are getting on in the game and your",
    "stats for the games you’ve played (including wins and losses).",
    "",
    "Once a game has been found in either ranked or quick matchmaking, you have the option to select which character you would like",
    "to be for the match. The options provided are Fire, Water, Earth and Air. More details for these characters and their backgrounds",
    "can be found on the project website.",
    "",
    "After you and your opponent have selected your characters, you will be taken to the match screen where you will be shown the",
    "different moves you can do on your turn. These are dependent on the number of points you have for each turn. Any moves you",
    "cannot do will be shaded out and any move you can do with your points will be highlighted blue and available for you to select. Each",
    "move shows the cost and either damage, health and/or points that will be given/received for each turn. Your health and points will",
    "be displayed in the top left corner below the health bar.",
    ], 
};